/* ═══════════════════════════════════════════════════════════
   Catalog Data — Master exercise index (embedded for V1)
   ═══════════════════════════════════════════════════════════ */

import type { CatalogEntry } from '../shared/types';

export const catalogData: CatalogEntry[] = [
  {
    id: 'first-index-of',
    slug: 'first-index-of',
    title: 'First Index Of',
    summary: 'Return the first index of target in the array.',
    topic: 'arrays',
    difficulty: 'easy',
    tags: ['linear-search'],
    estimatedMinutes: 10,
    order: 1,
    mode: 'function_implementation',
  },
  {
    id: 'two-sum-basic',
    slug: 'two-sum-basic',
    title: 'Two Sum Basic',
    summary: 'Find two indices whose values add up to a target.',
    topic: 'arrays',
    difficulty: 'easy',
    tags: ['array-traversal', 'hash-map'],
    estimatedMinutes: 15,
    order: 2,
    mode: 'function_implementation',
  },
  {
    id: 'reverse-array',
    slug: 'reverse-array',
    title: 'Reverse Array',
    summary: 'Reverse an integer array in place.',
    topic: 'arrays',
    difficulty: 'easy',
    tags: ['two-pointers'],
    estimatedMinutes: 10,
    order: 3,
    mode: 'function_implementation',
  },
  {
    id: 'max-element',
    slug: 'max-element',
    title: 'Maximum Element',
    summary: 'Find the maximum element in an array.',
    topic: 'arrays',
    difficulty: 'easy',
    tags: ['array-traversal'],
    estimatedMinutes: 8,
    order: 4,
    mode: 'function_implementation',
  },
  {
    id: 'count-occurrences',
    slug: 'count-occurrences',
    title: 'Count Occurrences',
    summary: 'Count how many times a target appears in an array.',
    topic: 'arrays',
    difficulty: 'easy',
    tags: ['linear-search', 'counting'],
    estimatedMinutes: 10,
    order: 5,
    mode: 'function_implementation',
  },
  {
    id: 'is-palindrome',
    slug: 'is-palindrome',
    title: 'Is Palindrome',
    summary: 'Check whether a given string is a palindrome.',
    topic: 'strings',
    difficulty: 'easy',
    tags: ['two-pointers', 'string-comparison'],
    estimatedMinutes: 12,
    order: 1,
    mode: 'function_implementation',
  },
  {
    id: 'reverse-string',
    slug: 'reverse-string',
    title: 'Reverse String',
    summary: 'Reverse a string without using built-in reverse.',
    topic: 'strings',
    difficulty: 'easy',
    tags: ['string-builder'],
    estimatedMinutes: 10,
    order: 2,
    mode: 'function_implementation',
  },
  {
    id: 'fizz-buzz',
    slug: 'fizz-buzz',
    title: 'FizzBuzz',
    summary: 'Print numbers from 1 to n with Fizz/Buzz replacements.',
    topic: 'loops',
    difficulty: 'easy',
    tags: ['conditionals', 'modulo'],
    estimatedMinutes: 10,
    order: 1,
    mode: 'function_implementation',
  },
  {
    id: 'sum-digits',
    slug: 'sum-digits',
    title: 'Sum of Digits',
    summary: 'Compute the sum of digits of a positive integer.',
    topic: 'loops',
    difficulty: 'easy',
    tags: ['math', 'modulo'],
    estimatedMinutes: 10,
    order: 2,
    mode: 'function_implementation',
  },
  {
    id: 'binary-search',
    slug: 'binary-search',
    title: 'Binary Search',
    summary: 'Search for a target in a sorted array using binary search.',
    topic: 'searching',
    difficulty: 'medium',
    tags: ['divide-and-conquer'],
    estimatedMinutes: 20,
    order: 1,
    mode: 'function_implementation',
  },
  {
    id: 'bubble-sort',
    slug: 'bubble-sort',
    title: 'Bubble Sort',
    summary: 'Sort an array using the bubble sort algorithm.',
    topic: 'sorting',
    difficulty: 'medium',
    tags: ['comparison-sort'],
    estimatedMinutes: 20,
    order: 1,
    mode: 'function_implementation',
  },
  {
    id: 'factorial',
    slug: 'factorial',
    title: 'Factorial',
    summary: 'Compute the factorial of a non-negative integer.',
    topic: 'recursion',
    difficulty: 'easy',
    tags: ['math'],
    estimatedMinutes: 10,
    order: 1,
    mode: 'function_implementation',
  },
  {
    id: 'fibonacci',
    slug: 'fibonacci',
    title: 'Fibonacci Number',
    summary: 'Return the n-th Fibonacci number.',
    topic: 'recursion',
    difficulty: 'easy',
    tags: ['dynamic-programming'],
    estimatedMinutes: 12,
    order: 2,
    mode: 'function_implementation',
  },
  {
    id: 'simple-counter',
    slug: 'simple-counter',
    title: 'Simple Counter',
    summary: 'Implement a counter class with increment and getValue.',
    topic: 'classes',
    difficulty: 'easy',
    tags: ['constructor', 'state'],
    estimatedMinutes: 15,
    order: 1,
    mode: 'class_implementation',
  },
  {
    id: 'is-even',
    slug: 'is-even',
    title: 'Is Even',
    summary: 'Determine whether a number is even or odd.',
    topic: 'conditionals',
    difficulty: 'easy',
    tags: ['modulo'],
    estimatedMinutes: 5,
    order: 1,
    mode: 'function_implementation',
  },

  // ── New exercises (M3 batch) ──

  {
    id: 'contains-duplicate',
    slug: 'contains-duplicate',
    title: 'Contains Duplicate',
    summary: 'Check if any value appears at least twice in the array.',
    topic: 'arrays',
    difficulty: 'easy',
    tags: ['hash-set'],
    estimatedMinutes: 10,
    order: 6,
    mode: 'function_implementation',
  },
  {
    id: 'merge-sorted-arrays',
    slug: 'merge-sorted-arrays',
    title: 'Merge Sorted Arrays',
    summary: 'Merge two sorted arrays into a single sorted array.',
    topic: 'arrays',
    difficulty: 'medium',
    tags: ['two-pointers', 'merge'],
    estimatedMinutes: 20,
    order: 7,
    mode: 'function_implementation',
  },
  {
    id: 'power-of-two',
    slug: 'power-of-two',
    title: 'Power of Two',
    summary: 'Determine if a given integer is a power of two.',
    topic: 'math',
    difficulty: 'easy',
    tags: ['bit-manipulation'],
    estimatedMinutes: 8,
    order: 1,
    mode: 'function_implementation',
  },
  {
    id: 'gcd',
    slug: 'gcd',
    title: 'Greatest Common Divisor',
    summary: 'Find the GCD of two positive integers using Euclidean algorithm.',
    topic: 'math',
    difficulty: 'easy',
    tags: ['euclidean'],
    estimatedMinutes: 12,
    order: 2,
    mode: 'function_implementation',
  },
  {
    id: 'selection-sort',
    slug: 'selection-sort',
    title: 'Selection Sort',
    summary: 'Sort an array using the selection sort algorithm.',
    topic: 'sorting',
    difficulty: 'medium',
    tags: ['comparison-sort'],
    estimatedMinutes: 20,
    order: 2,
    mode: 'function_implementation',
  },
  {
    id: 'count-vowels',
    slug: 'count-vowels',
    title: 'Count Vowels',
    summary: 'Count the number of vowels in a string.',
    topic: 'strings',
    difficulty: 'easy',
    tags: ['string-traversal'],
    estimatedMinutes: 8,
    order: 3,
    mode: 'function_implementation',
  },
  {
    id: 'hello-world',
    slug: 'hello-world',
    title: 'Hello World',
    summary: 'Print "Hello, World!" to standard output.',
    topic: 'loops',
    difficulty: 'easy',
    tags: ['intro', 'output'],
    estimatedMinutes: 3,
    order: 0,
    mode: 'main_program',
  },
  {
    id: 'sum-array',
    slug: 'sum-array',
    title: 'Sum of Array',
    summary: 'Compute the sum of all elements in an integer array.',
    topic: 'arrays',
    difficulty: 'easy',
    tags: ['accumulator'],
    estimatedMinutes: 8,
    order: 0,
    mode: 'function_implementation',
  },
  {
    id: 'min-stack',
    slug: 'min-stack',
    title: 'MinStack',
    summary: 'Design a stack that supports push, pop, and retrieving the minimum element.',
    topic: 'classes',
    difficulty: 'medium',
    tags: ['stack', 'design'],
    estimatedMinutes: 25,
    order: 2,
    mode: 'class_implementation',
  },
  {
    id: 'is-prime',
    slug: 'is-prime',
    title: 'Is Prime',
    summary: 'Determine whether a given number is prime.',
    topic: 'math',
    difficulty: 'easy',
    tags: ['loop', 'optimization'],
    estimatedMinutes: 10,
    order: 3,
    mode: 'function_implementation',
  },
];
